# Generated by Django 4.0 on 2022-01-08 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default=datetime.datetime(2022, 1, 8, 9, 40, 32, 797162, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
