# Generated by Django 4.0 on 2022-01-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsapp', '0003_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
