# Generated by Django 4.0 on 2022-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsapp', '0004_remove_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
